# Default values for percona-openebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: percona/percona-xtradb-cluster-operator
  tag: 1.8.0
  pullPolicy: IfNotPresent

# set if you want to specify a namespace to watch
# defaults to `.Release.namespace` if left blank
# watchNamespace:

# set if you want to use a different operator name
# defaults to `percona-xtradb-cluster-operator`
# operatorName:

# set to false if you don't want the helm chart to
# automatically create the CRD.
createCRD: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

pxc:
  size: 3
  image: percona/percona-xtradb-cluster:8.0.22-13.1
  autoRecovery: true
  storageClass: local-hostpath
  storage: 6G
  
haproxy:
  enabled: true
  size: 3
  image: percona/percona-xtradb-cluster-operator:1.8.0-haproxy

proxysql:
  enabled: false
  size: 3
  image: percona/percona-xtradb-cluster-operator:1.8.0-proxysql

pmm:
  enabled: false
  image: percona/pmm-client:2.12.0
  serverHost: monitoring-service
  serverUser: admin
