{{- if .Values.type.installDirector -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      name: memcached
  replicas: 1
  template:
    metadata:
      labels:
        name: memcached
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: memcached
        image: {{ template "memcachedImage" . }}
        imagePullPolicy: IfNotPresent
        args:
        - -m 64 # Maximum memory to use, in megabytes. 64MB is variablename.
        - -p 11211 # Default port, but being explicit is nice.
        ports:
        - name: clients
          containerPort: 11211
        securityContext:
          runAsUser: 1000
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}
{{- end }}
