kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-gateway-server
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "endpoints"]
  verbs: ["get", "list", "watch"]
