kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-gateway-server
subjects:
- kind: ServiceAccount
  name: agent-gateway-server
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: agent-gateway-server
  apiGroup: rbac.authorization.k8s.io
