apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: agent-gateway
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: agent-gateway-server
          servicePort: 8080
        path: /agent/(.*)
      - backend:
          serviceName: agent-gateway-server
          servicePort: 8081
        path: /agent/debug/(.*)
    host: {{ .Values.domain }}
