{{- if .Values.type.installDirector -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayastore
spec:
  storageClassName: {{ .Values.mayaStore.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mayaStore.storageCapacity }}
{{- end }}
