{{- if .Values.type.installDirector -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: od-elasticsearch-logging
  name: od-elasticsearch-logging
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: od-elasticsearch-logging
{{- end }}
