{{- if .Values.type.installDirector -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-manager
spec:
  selector:
    matchLabels:
      name: table-manager
  replicas: 1
  template:
    metadata:
      labels:
        name: table-manager
    spec:
      serviceAccountName: sa-maya-io
      initContainers:
      - name: init-agent
        image: {{ .Values.imageRegistry }}/maya-init:1.0.0
        command:
        - sh
        - "-c"
        - |
          set -ex
          export MAYA=$(kubectl get ClusterRoleBinding | grep -w crb-maya-io | awk '{print $1}')
          echo $MAYA
          until [ ! -z "$MAYA" ]
          do
             echo "wating for ClusterRoleBinding"
             sleep 1;
             export MAYA=$(kubectl get ClusterRoleBinding | grep -w crb-maya-io | awk '{print $1}')
             echo $MAYA
          done
      - name: tm-wait-for-cassandra
        image: {{ .Values.imageRegistry }}/maya-init:1.0.0
        command:
        - sh
        - "-c"
        - |
          set -ex
          export COUNT=0
          echo $COUNT
          until [ $COUNT -ne 0 ]
          do
             echo "wating for cassandra"
             sleep 2;
             export COUNT=$(kubectl get pods -l app=cassandra -n {{ .Release.Namespace }} -o json  | jq -r '.items[] | select(.status.phase == "Running" and ([ .status.conditions[] | select(.type == "Ready" and .status == "True") ] | length ) >= 1 ) | .metadata.name' | grep -w cassandra | wc -l)
             echo $COUNT
          done
      containers:
      - name: table-manager
        image: {{ template "table-manager" . }}
        imagePullPolicy: IfNotPresent
        args:
        - -server.http-listen-port=80
        - -dynamodb.original-table-name=cortex
        - -chunk.storage-client=cassandra
        - -cassandra.addresses=cassandra.{{ .Release.Namespace }}.svc.{{ .Values.server.clusterDomain }}
        - -cassandra.keyspace=mayacortex
        - -cassandra.replication-factor={{ .Values.cortex.replicationFactor }}
        - -cassandra.timeout={{ .Values.cortex.timeout }}
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2017-01-06
        - -dynamodb.chunk-table.from=2017-04-17
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}
{{- end }}
