{{- if .Values.type.installDirector -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configs-db
spec:
  selector:
    matchLabels:
      name: configs-db
  replicas: 1
  template:
    metadata:
      labels:
        name: configs-db
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: configs-db
        image: {{ template "configs-dbImage" . }}
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_DB
            value: configs
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}
{{- end -}}
