{{- if .Values.type.installDirector -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-agent
  labels:
    name: cloud-agent
    app: cloud-agent
spec:
  selector:
    matchLabels:
      name: cloud-agent
  replicas: 1
  template:
    metadata:
      labels:
        name: cloud-agent
        app: cloud-agent
    spec:
      containers:
        - name: cloud-agent
          image: {{ .Values.imageRegistry }}/cloud-agent:{{ .Values.server.release }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8880
              protocol: TCP
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}
{{- end -}}